version: '3.8'

services:
  web:
    build: .
    ports:
      - "8071:8071"
    volumes:
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=all
      - TRANSFORMERS_CACHE=/app/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped 